language: node_js
node_js:
  - 12

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker --version
  - tag=$(git rev-parse --short $TRAVIS_COMMIT)
  - docker build -t udagram-api-feed udagram-api-feed/
  - docker tag udagram-api-feed ioannisioannou16/udagram-api-feed:$tag
  - docker build -t udagram-api-user udagram-api-user/
  - docker tag udagram-api-user ioannisioannou16/udagram-api-user:$tag
  - docker build -t udagram-api-nginx udagram-api-nginx/
  - docker tag udagram-api-nginx ioannisioannou16/udagram-api-nginx:$tag
  - docker build -t udagram-frontend udagram-frontend/
  - docker tag udagram-frontend ioannisioannou16/udagram-frontend:$tag
after_success:
  - docker push ioannisioannou16/udagram-api-feed
  - docker push ioannisioannou16/udagram-api-user
  - docker push ioannisioannou16/udagram-api-nginx
  - docker push ioannisioannou16/udagram-frontend
