apiVersion: v1
kind: Service
metadata:
  name: udagram-api-nginx
  labels:
    app: udagram-api-nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: udagram-api-nginx
